function isGreater = isFiringRateGreaterThanMin(ES, minFiringRate)

isGreater = any(ES.averageFiringRatesBySpdf.preEnterFixation.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.postEnterFixation.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.postEnterFixationLate.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.preCueBaseline.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.cueResponse.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.cueTargetDelay.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.arrayHoldResponse.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.arrayRelResponse.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.targetDimDelay.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.targetDimResponse.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.preExitFixation.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.postExitFixation.byLoc >= minFiringRate);