function isGreater = isFiringRateGreaterThanMin(ES, minFiringRate)

isGreater = any(ES.averageFiringRatesBySpdf.postEnterFixation.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.postEnterFixationLate.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.preCueBaseline.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.cueResponse.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.cueTargetDelay.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.arrayResponseHoldBal.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.arrayResponseRelBal.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.targetDimDelayBal.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.targetDimResponseBal.byLoc >= minFiringRate) || ...
            any(ES.averageFiringRatesBySpdf.preExitFixation.byLoc >= minFiringRate);