clear;
sessionInd = 8;
processedDataRootDir = 'Y:/gratings-task-analysis/processed_data/';
dataDirRoot = 'Z:/McCartney/merged';
muaDataDirRoot = 'Y:/simple-mua-detection/processed_data/';
suaMuaDataDirRoot = muaDataDirRoot;
recordingInfoFileName = 'C:/Users/Ryan/Documents/MATLAB/gratings-task-analysis/recordingInfo2.csv';
channelsToLoad = 58;
muaChannelsToLoad = 1;
isZeroDistractors = 0;
numRandomizations = 2;
isLoadSortedSua = 1;
isLoadMua = 0;