function quickImagePlotAllEventsRowRunner(groupName, isIncluded, spdfInfo, ...
        cueOnsetT, arrayOnsetT, targetDimT, exitFixationT, ...
        summaryDataDir, v)

fprintf('\n');
fprintf('Plotting normalized mean SPDFs for group %s...\n', groupName);

cueOnsetSpdfInRFNormSub = (spdfInfo.cueOnsetSpdfInRFNorm(isIncluded,:));
cueOnsetSpdfExRFNormSub = (spdfInfo.cueOnsetSpdfExRFNorm(isIncluded,:));
arrayOnsetHoldSpdfInRFNormSub = (spdfInfo.arrayOnsetHoldSpdfInRFNorm(isIncluded,:));
arrayOnsetHoldSpdfExRFNormSub = (spdfInfo.arrayOnsetHoldSpdfExRFNorm(isIncluded,:));
targetDimSpdfInRFNormSub = (spdfInfo.targetDimSpdfInRFNorm(isIncluded,:));
targetDimSpdfExRFNormSub = (spdfInfo.targetDimSpdfExRFNorm(isIncluded,:));
exitFixationSpdfInRFNormSub = (spdfInfo.exitFixationSpdfInRFNorm(isIncluded,:));
exitFixationSpdfExRFNormSub = (spdfInfo.exitFixationSpdfExRFNorm(isIncluded,:));

fprintf('\t%s: %d units\n', groupName, sum(isIncluded));

plotFileName = sprintf('%s/allSessions-%s-imagePopDiffSpdfs4-v%d.png', summaryDataDir, groupName, v);
isDiff = 1;
quickImagePlotAllEvents4InARow(...
        cueOnsetSpdfInRFNormSub - cueOnsetSpdfExRFNormSub, ...
        arrayOnsetHoldSpdfInRFNormSub - arrayOnsetHoldSpdfExRFNormSub, ...
        targetDimSpdfInRFNormSub - targetDimSpdfExRFNormSub, ...
        exitFixationSpdfInRFNormSub - exitFixationSpdfExRFNormSub, ...
        cueOnsetT, arrayOnsetT, targetDimT, exitFixationT, ...
        groupName, isDiff, plotFileName);

plotFileName = sprintf('%s/allSessions-%s-imagePopInRFSpdfs4-v%d.png', summaryDataDir, groupName, v);
isDiff = 0;
quickImagePlotAllEvents4InARow(...
        cueOnsetSpdfInRFNormSub, ...
        arrayOnsetHoldSpdfInRFNormSub, ...
        targetDimSpdfInRFNormSub, ...
        exitFixationSpdfInRFNormSub, ...
        cueOnsetT, arrayOnsetT, targetDimT, exitFixationT, ...
        groupName, isDiff, plotFileName);
